### PR TITLE
refactor imports on flow boost and eigen

### PR DESCRIPTION
**Pull request by ravescovi**

### CODE REVIEW

**Comment by NickolausDS** [comment]
Any reason to switch out form the dotted string imports? Those will still be supported in this package due to gladier-xpcs being needed by the portal and the alcf-data-portal.

**Comment by NickolausDS** [comment]
Any reason to switch out form the dotted string imports? Those will still be supported in this package due to gladier-xpcs being needed by the portal and the alcf-data-portal.

**Comment by ravescovi** [comment]
I am just trying to keep our packages consistent with the "non-package" approach we agreed on the template. Currently, we don't need to install the package anymore on the portal since there are no more self-importing functions (I think).

**Comment by NickolausDS** [comment]
The "non-package" approach in the template was more to show a simple starting point for new people creating Gladier clients, I don't think there's a reason to apply the same thing to our existing xpcs/ssx tooling.

For XPCS specifically, I don't think there's a real need to do dotted import strings vs explicit classes, but since XPCS is a package dotted import strings are a bit cleaner, and I'm a bit preferential towards them.

**Comment by ravescovi** [comment]
Ok. I agree, closing this PR until further discussion.

**Pull request closed without merging**
