### PR TITLE
Add 'xpcs' tag to all runs

### PR DESCRIPTION
**Pull request by NickolausDS**

### CODE REVIEW

**Review by ravescovi — APPROVED** [review]
Can you also add 'aps', 'xpcs', 'q1' ?
Otherwise, go ahead and merge.

**Comment by NickolausDS** [comment]
What's `q1` stand for? If quarter, should that be `q2`?

**Comment by ravescovi** [comment]
yes. It was just an example. We can also gather that from the DM step

**Comment by NickolausDS** [comment]
I added 'aps' to the tags, I think I'll keep it there for now and we can decide on more complex behavior in a separate PR.

**Pull request merged**
